apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway
- resource-manager
- sidecar
- task-dispatcher
- task-manager
- namespace.yaml
images:
- name: cornserve/gateway
  newName: docker.io/cornserve/gateway
  newTag: v0.0.1.post2
- name: cornserve/resource-manager
  newName: docker.io/cornserve/resource-manager
  newTag: v0.0.1.post2
- name: cornserve/sidecar
  newName: docker.io/cornserve/sidecar
  newTag: v0.0.1.post2
- name: cornserve/task-dispatcher
  newName: docker.io/cornserve/task-dispatcher
  newTag: v0.0.1.post2
- name: cornserve/task-manager
  newName: docker.io/cornserve/task-manager
  newTag: v0.0.1.post2
configMapGenerator:
- name: cornserve-config
  namespace: cornserve
  behavior: merge
  literals:
  - CORNSERVE_IMAGE_PREFIX=docker.io/cornserve
  - CORNSERVE_IMAGE_PULL_POLICY=IfNotPresent
  - CORNSERVE_IMAGE_TAG=v0.0.1.post2
